config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: 'new_product'
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: 'product'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  resources :products, path: "/"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  before_validation :format_price
  validates :title, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true, length: { minimum: 10 }
  has_one_attached :photo

  enum status: { active: 1, inactive: 0 }

  private

  def format_price
    # Redondea el precio a dos decimales si está presente
    self.price = price.round(2) if price.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # Muestra una lista de todos los productos activos.
  def index
    @products = Product.where(status: 1) # Filtra solo productos activos
  end

  # Muestra los detalles de un producto específico.
  def show
    @product = Product.find(params[:id])
  end

  # Renderiza el formulario para crear un nuevo producto.
  def new
    @product = Product.new
  end

  # Crea un nuevo producto con los parámetros proporcionados.
  # Si se guarda correctamente, redirige a la lista de productos.
  # Si no, renderiza el formulario de nuevo con errores.
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Renderiza el formulario para editar un producto existente.
  def edit
    @product = Product.find(params[:id])
  end

  # Actualiza un producto existente con los parámetros proporcionados.
  # Si se actualiza correctamente, redirige a la lista de productos.
  # Si no, renderiza el formulario de edición con errores.
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # Realiza un borrado lógico de un producto existente y redirige a la lista de productos
  # con un mensaje de confirmación.
  def destroy
    @product = Product.find(params[:id])
    @product.update(status: 0) # Cambia el estado del producto a 0 (inactivo o eliminado)
    redirect_to products_path, notice: "Tu producto se ha marcado como eliminado correctamente", status: :see_other
  end

  private

  # Define los parámetros permitidos para crear o actualizar un producto.
  def product_params
    params.require(:product).permit(:title, :price, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Vendelo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h2>Editar producto</h2>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Productos</h1>

<% @products.each do |product| %>
  <%= link_to product_path(product.id) do %>
    <h3>
      <%= product.title %>
    </h3>
    <span>
    <p>
      <%= product.description %>
    </p>
  </span>
  <hr size="1px" color="gray"/>
  <% end %>

<% end %>

app/views/products/new.html.erb
<h2>Añadir producto</h2>

<%= render 'form' %>

app/views/products/show.html.erb
<h1>
  <%= @product.title %>
</h1>

<span>
  <img src="<%= url_for(@product.photo) if @product.photo.attached? %>" alt="<%= @product.title %>" width="300px">
</span>

<p>
  <%= @product.description %>
</p>

<span>
  $<%= @product.price %>
</span>

<%= link_to 'Editar', edit_product_path(@product) %>
<%= link_to 'Eliminar', product_path(@product), data: {
  turbo_method: :delete,
  turbo_confirm: '¿Estás seguro de que quieres eliminar este producto?'
}%>

app/views/shared/_header.html.erb
<div class="bg-white flex justify-between items-center px-2">
  <%= link_to products_path do %>
  <h1 class="text-2xl font-bold text-teal-500">
  Shopify
  </h1>
  <% end %>

  <%= link_to 'Añadir producto', new_product_path %>
</div>